var ControlSecurityKey = Object.freeze({
    GeneralTitle: 'general_Title',
    GeneralCategory: 'general_Category',
    GeneralHideTask: 'general_HideTask',
    GeneralGroupTask: 'general_GroupTask',

    LocationAddress: 'location_Address',

    IntervalGlobalWeeks: 'interval_GlobalWeeks',
    IntervalGlobalShedule: 'interval_GlobalShedule',
    IntervalGlobalDate: 'interval_GlobalDate',
    IntervalLocalWeeks: 'interval_LocalWeeks',
    IntervalLocalShedule: 'interval_LocalShedule',
    IntervalLocalDate: 'interval_LocalDate',

    GuideGlobalDescription: 'guide_GlobalDescription',
    GuideGlobalImages: 'guide_GlobalImages',
    GuideGlobalVideos: 'guide_GlobalVideos',
    GuideLocalDescription: 'guide_LocalDescription',
    GuideLocalImages: 'guide_LocalImages',
    GuideLocalVideos: 'guide_LocalVideos',
    GuideRemoveComment: 'guide_RemoveComment',

    DocumentGlobalDocument: 'document_GlobalDocument',
    DocumentLocalDocument: 'document_LocalDocument',

    AssignDepartments: 'assign_Departments',

    AssignEstimate: 'estimate',
    AssignTeam: 'team',

    DayAssignEstimate: 'dayAssign_Estimate',
    DayAssignDaysPerWeek: 'dayAssign_DaysPerWeek',
    DayAssignTeam: 'dayAssign_Team',
    DayAssignOpenTask: 'dayAssign_OpenTask',
    DayAssignCancelTask: 'dayAssign_CancelTask',
    DayAssignReOpenTask: 'dayAssign_ReOpenTask',

    OperationalTaskCategory: 'category',
    OperationalTaskDate: 'date',
    OperationalTaskEstimatedTime: 'estimatedTime',
    OperationalTaskTitle: 'title',
    OperationalTaskDescription: 'description',
    OperationalTaskAddress: 'address',
    OperationalTaskDocuments: 'documents',
    OperationalTaskResponsible: 'responsible',
    OperationalTaskHousingDepartment: 'housingDepartment',
    OperationalTaskTeneantType: 'tenantType',
    OperationalTaskTime: 'time',
    OperationalTaskNameOfResident: 'nameOfResident',
    OperationalTaskPhone: 'phone',
    OperationalTaskComment: 'comment',
    OperationalTaskFileUploader: 'fileUploader',
    OperationalTaskDeleteDocument: 'deleteDocument',
    OperationalTaskCancel: 'cancelTask',
    OperationalTaskReOpen: 'reOpenTask',
    OperationalTaskUrgent: 'urgent',
    OperationalTaskSaveButton: 'saveNewOperationalTask',
    OperationalTaskAssignButton: 'assignNewOperationalTask',
    OperationalTaskOpenButton: 'openNewOperationalTask',

    WeekPlanPage: 'weekPlan_Page',
    YearPlanPage: 'yearPlan_Page',
    MyTasksPage: 'myTasks_Page',
    HistoryPage: 'history_Page',
    GroupsPage: 'groups_Page',
    SetupPage: 'setup_Page',
    FacilityTaskCreatePage: 'facilityTask_Create_Page',
    FacilityTaskEditPage: 'facilityTask_Edit_Page',
    AdHockTaskPage: 'adHockTask_Page',
    TenantTaskPage: 'tenantTask_Page',
    OtherTaskPage: 'otherTask_Page',
    StatisticsPage: 'statistics_Page'
});